### ISSUE TITLE
CLI to generate pyi

### ISSUE THREAD

**Issue by realkarych** [realkarych/rxconf#70]
Currently we cannot provide static analysis for RxConf instance.

Idea: according to the state of rxconf generate pyi file contains annotations for attributes' tree.
Do this via CLI: `rxconf annotate <path/to/config> <destination/config.pyi>`

**Comment by klukashka** [comment]
After working on this issue I found out that it is difficult implement such suggestions in IDE. The reasons are:
- IDE does not know what will be stored in your rxconf variable, so you have to create something which can describe your variable before running code.
- You cannot describe your variable just in .pyi file because it is an interface and your object should exist in python file. Creating a .py file is a bad idea.
- We can implement __dir__ method overriding. The object will suggest proper attributes when being dynamically analyzed. However, there is not much sense because it can be used only in jupiter notebooks and rxconf lib is not supposed for them.
